### ISSUE TITLE
ego sync stopped working with KeyError: 'default' Error

### ISSUE THREAD

**Issue by zdavatz** [funtoo/ego#18]
Since this morning ego sync gives me this error:
```
Already on 'master'
Your branch and 'origin/master' have diverged,
and have 81 and 357 different commits each, respectively.
  (use "git pull" to merge the remote branch into yours)
HEAD is now at 4b86423 changes
Skipping repository kits/python-modules-kit/
Automatic merge went well; stopped before committing as requested
Traceback (most recent call last):
  File "/usr/bin/ego", line 96, in <module>
    EgoModule.run_ego_module(action, econfig, args, VERSION)
  File "/usr/share/ego/python/ego/module.py", line 78, in run_ego_module
    ego_module(*args)
  File "/usr/share/ego/python/ego/module.py", line 63, in __call__
    self.handle(**options)
  File "/usr/share/ego/modules/sync.ego", line 224, in handle
    self.sync_meta_repo(**options)
  File "/usr/share/ego/modules/sync.ego", line 200, in sync_meta_repo
    success = self.sync_kit(kt, branch=branch)
  File "/usr/share/ego/modules/sync.ego", line 33, in sync_kit
    branch = self.config.kit_info_metadata["kit_settings"][kit_name]["default"]
KeyError: 'default'
```

**Comment by zdavatz** [comment]
Using this version via git seems to work just fine.

**Comment by zdavatz** [comment]
This error is gone with Ego 2.4.2
