### ISSUE TITLE
Running `ego sync` results in error

### ISSUE THREAD

**Issue by zdavatz** [funtoo/ego#27]
1. I cloned https://github.com/funtoo/ego.git
2. Now running: `./ego sync`
3. Results in:
```
ERROR: Ego encountered an unexpected error: SyntaxError
ERROR: Full traceback written to /tmp/ego-traceback-16204.txt.
```
4. Log is:
```
invalid syntax (sync.ego, line 296)Traceback (most recent call last):
  File "./ego", line 120, in <module>
    EgoModule.run_ego_module(action, econfig, args, VERSION)
  File "/var/git/ego/python/ego/module.py", line 107, in run_ego_module
    mod = loader.load_module()
  File "<frozen importlib._bootstrap>", line 539, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1614, in load_module
  File "<frozen importlib._bootstrap>", line 596, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 1220, in load
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1467, in exec_module
  File "<frozen importlib._bootstrap>", line 1572, in get_code
  File "<frozen importlib._bootstrap>", line 1532, in source_to_code
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/var/git/ego/modules/sync.ego", line 296
    Output.warning(f"Skipping kit {kt} due to skip setting in /etc/ego.conf.")
                                                                            ^
SyntaxError: invalid syntax
```
5. Any hints?

**Comment by zdavatz** [comment]
This is due to the fact, that the `ego` version `2.8.6` needs at least `Python 3.7.7` to work.
